-- MySQL Script generated by MySQL Workbench
-- Tue Feb  3 11:03:22 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema samt3d
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema samt3d
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `samt3d` DEFAULT CHARACTER SET utf8 ;
USE `samt3d` ;

-- -----------------------------------------------------
-- Table `samt3d`.`classrooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `classrooms` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `class_num` INT NULL,
  `isDoorOpen` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `samt3d`.`subjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `subjects` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `class_id` INT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`class_id`)
  REFERENCES `samt3d`.`classrooms` (`id`)
  ON DELETE CASCADE
  ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `samt3d`.`statistics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `statistics` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `developer_percent` FLOAT NULL,
  `system_engineers_percent` FLOAT NULL,
  `daily_player` INT NULL,
  `classrom_visited` INT NULL,
  `visiting_time` TIME NULL,
  `subject_id` INT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`subject_id`)
  REFERENCES `samt3d`.`subjects` (`id`)
  ON DELETE CASCADE
  ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `samt3d`.`descriptions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `descriptions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `samt3d`.`posters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `posters` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `image_url` VARCHAR(255) NULL,
  `class_id` INT NULL,
  `description_id` INT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`class_id`)
  REFERENCES `samt3d`.`classrooms` (`id`)
  ON DELETE CASCADE
  ON UPDATE CASCADE,
  FOREIGN KEY (`description_id`)
  REFERENCES `samt3d`.`descriptions` (`id`)
  ON DELETE CASCADE
  ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `samt3d`.`audio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `audio` (
  `id` INT ZEROFILL NOT NULL,
  `audio_url` VARCHAR(255) NULL,
  `description_id` INT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`description_id`)
  REFERENCES `samt3d`.`descriptions` (`id`)
  ON DELETE CASCADE
  ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `samt3d`.`npcs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `npcs` (
  `id` INT ZEROFILL NOT NULL,
  `class_id` INT NULL,
  `description_id` INT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`class_id`)
  REFERENCES `samt3d`.`classrooms` (`id`)
  ON DELETE CASCADE
  ON UPDATE CASCADE,
  FOREIGN KEY (`description_id`)
  REFERENCES `samt3d`.`descriptions` (`id`)
  ON DELETE CASCADE
  ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `samt3d`.`quizzes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quizzes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `question` VARCHAR(255) NULL,
  `answer` VARCHAR(255) NULL,
  `class_id` INT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`class_id`)
  REFERENCES `samt3d`.`classrooms` (`id`)
  ON DELETE CASCADE
  ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
