-- MySQL Script generated by MySQL Workbench
-- Tue Feb  3 11:03:22 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SAMT3D
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SAMT3D
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SAMT3D` DEFAULT CHARACTER SET utf8 ;
USE `SAMT3D` ;

-- -----------------------------------------------------
-- Table `SAMT3D`.`classrooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAMT3D`.`classrooms` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `class_num` INT NULL,
  `isDoorOpen` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAMT3D`.`subjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAMT3D`.`subjects` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `class_id` INT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`class_id`)
  REFERENCES `SAMT3D`.`classrooms` (`id`)
  ON DELETE CASCADE
  ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAMT3D`.`statistics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAMT3D`.`statistics` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `developer_percent` FLOAT NULL,
  `system_engineers_percent` FLOAT NULL,
  `daily_player` INT NULL,
  `classrom_visited` INT NULL,
  `visiting_time` TIME NULL,
  `subject_id` INT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`subject_id`)
  REFERENCES `SAMT3D`.`subjects` (`id`)
  ON DELETE CASCADE
  ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAMT3D`.`descriptions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAMT3D`.`descriptions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAMT3D`.`posters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAMT3D`.`posters` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `image_url` VARCHAR(255) NULL,
  `class_id` INT NULL,
  `description_id` INT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`class_id`)
  REFERENCES `SAMT3D`.`classrooms` (`id`)
  ON DELETE CASCADE
  ON UPDATE CASCADE,
  FOREIGN KEY (`description_id`)
  REFERENCES `SAMT3D`.`descriptions` (`id`)
  ON DELETE CASCADE
  ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAMT3D`.`audio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAMT3D`.`audio` (
  `id` INT ZEROFILL NOT NULL,
  `audio_url` VARCHAR(255) NULL,
  `description_id` INT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`description_id`)
  REFERENCES `SAMT3D`.`descriptions` (`id`)
  ON DELETE CASCADE
  ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SAMT3D`.`npcs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SAMT3D`.`npcs` (
  `id` INT ZEROFILL NOT NULL,
  `class_id` INT NULL,
  `description_id` INT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`class_id`)
  REFERENCES `SAMT3D`.`classrooms` (`id`)
  ON DELETE CASCADE
  ON UPDATE CASCADE,
  FOREIGN KEY (`description_id`)
  REFERENCES `SAMT3D`.`descriptions` (`id`)
  ON DELETE CASCADE
  ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
