-- MySQL Script generated by MySQL Workbench
-- Tue Mar  3 14:47:00 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema samt3d
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema samt3d
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `samt3d` DEFAULT CHARACTER SET utf8 ;
USE `samt3d` ;

-- -----------------------------------------------------
-- Table `samt3d`.`descriptions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `samt3d`.`descriptions` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `samt3d`.`audio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `samt3d`.`audio` (
  `id` INT(10) UNSIGNED ZEROFILL NOT NULL,
  `audio_url` VARCHAR(255) NULL DEFAULT NULL,
  `description_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `description_id` (`description_id` ASC) VISIBLE,
  CONSTRAINT `audio_ibfk_1`
    FOREIGN KEY (`description_id`)
    REFERENCES `samt3d`.`descriptions` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `samt3d`.`classrooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `samt3d`.`classrooms` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `class_num` INT(11) NULL DEFAULT NULL,
  `isDoorOpen` TINYINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `samt3d`.`npcs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `samt3d`.`npcs` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `class_id` INT(11) NULL DEFAULT NULL,
  `description_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `class_id` (`class_id` ASC) VISIBLE,
  INDEX `description_id` (`description_id` ASC) VISIBLE,
  CONSTRAINT `npcs_ibfk_1`
    FOREIGN KEY (`class_id`)
    REFERENCES `samt3d`.`classrooms` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `npcs_ibfk_2`
    FOREIGN KEY (`description_id`)
    REFERENCES `samt3d`.`descriptions` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `samt3d`.`posters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `samt3d`.`posters` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `image_url` VARCHAR(255) NULL DEFAULT NULL,
  `class_id` INT(11) NULL DEFAULT NULL,
  `description_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `class_id` (`class_id` ASC) VISIBLE,
  INDEX `description_id` (`description_id` ASC) VISIBLE,
  CONSTRAINT `posters_ibfk_1`
    FOREIGN KEY (`class_id`)
    REFERENCES `samt3d`.`classrooms` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `posters_ibfk_2`
    FOREIGN KEY (`description_id`)
    REFERENCES `samt3d`.`descriptions` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `samt3d`.`subjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `samt3d`.`subjects` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `class_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `subjects_ibfk_1` (`class_id` ASC) VISIBLE,
  CONSTRAINT `subjects_ibfk_1`
    FOREIGN KEY (`class_id`)
    REFERENCES `samt3d`.`classrooms` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `samt3d`.`statistics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `samt3d`.`statistics` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `developer_percent` FLOAT NULL DEFAULT NULL,
  `system_engineers_percent` FLOAT NULL DEFAULT NULL,
  `daily_player` INT(11) NULL DEFAULT NULL,
  `classroom_visited` INT(11) NULL DEFAULT NULL,
  `visiting_time` TIME NULL DEFAULT NULL,
  `subject_id` INT(11) NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  INDEX `subject_id` (`subject_id` ASC) VISIBLE,
  CONSTRAINT `statistics_ibfk_1`
    FOREIGN KEY (`subject_id`)
    REFERENCES `samt3d`.`subjects` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `samt3d`.`quiz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `samt3d`.`quiz` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `question` VARCHAR(255) NULL,
  `answer` VARCHAR(255) NULL,
  `class_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `class_id_idx` (`class_id` ASC) VISIBLE,
  CONSTRAINT `class_id`
    FOREIGN KEY (`class_id`)
    REFERENCES `samt3d`.`classrooms` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

USE `samt3d` ;

-- -----------------------------------------------------
-- Placeholder table for view `samt3d`.`total_daily_stats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `samt3d`.`total_daily_stats` (`stats_date` INT, `total_entries` INT, `total_players` INT, `total_classrooms_visited` INT, `total_developer_percent` INT, `total_system_engineers_percent` INT, `total_visiting_time` INT);

-- -----------------------------------------------------
-- View `samt3d`.`total_daily_stats`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `samt3d`.`total_daily_stats`;
USE `samt3d`;
CREATE  OR REPLACE VIEW `total_daily_stats` as 
select
	date(created_at) as stats_date,
	count(*) as total_entries,
	sum(daily_player) as total_players,
	sum(classroom_visited) as total_classrooms_visited,
	round(avg(developer_percent)) as total_developer_percent,
	round(avg(system_engineers_percent)) as total_system_engineers_percent,
	sec_to_time(sum(time_to_sec(visiting_time))) as total_visiting_time
from statistics
group by date(created_at);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
