services:
  db:
    image: ghcr.io/sebidb633/progettidocker/samt3d-db:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=''
      - MYSQL_DATABASE=SAMT3D
    volumes:
      - samt3d_db_data:/var/lib/mysql

  api:
    image: ghcr.io/sebidb633/progettidocker/samt3d-api:latest
    ports:
      - "4000:4000"
    restart: always
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql://root:root_password@db:3306/SAMT3D'

volumes:
  samt3d_db_data: