name: samt-3d

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Build the Docker image
      uses: actions/checkout@v4

    - name: Log in to Github Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push API image
      uses: docker/build-push-action@v5
      with:
        context: ./5_Sito/API
        push: true
        tags: ghcr.io/sebidb633/progettidocker/samt3d-api:latest
    
    - name: Build and Push DB image
      uses: docker/build-push-action@v5
      with:
        context: ./6_Database
        push: true
        tags: ghcr.io/sebidb633/progettidocker/samt3d-db:latest

# jobs:

#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v4
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag samt-3d:$(date +%s)
